### ISSUE TITLE
pytest fails after installation

### ISSUE THREAD

**Issue by lionlai1989** [centreborelli/sat-bundleadjust#9]
Hi, I follow the instructions in readme. 
1. Install package.  
2. Run pytest.  
3. Get the following errors:  
```
            for k in rpc.keys():
                print("rpc[k]:", rpc[k], "rpc_comp[k]:", rpc_comp[k])
>               assert np.allclose(rpc[k], rpc_comp[k])
E               assert False
E                +  where False = <function allclose at 0x7fd863508280>(674.484668082294, 674.501020878311)
E                +    where <function allclose at 0x7fd863508280> = np.allclose

tests/test_ba.py:49: AssertionError
```

I printed the value of two as follow:  
```
rpc[k]: 674.484668082294 rpc_comp[k]: 674.501020878311
```
Are there two values supposedly be closer? Right now the disparity is about `0.02`. I think it's quite a large value for RPC model. Does it mean that the bundle adjustment doesn't run successfully on my computer?  
Thanks.

**Comment by lionlai1989** [comment]
I checked the uncorrected value and it shows the bundle adjustment successfully modified the coefficient. It looks like the precision is not enough to make the tests pass. Is there a way to increase the precision to make the disparity smaller?

**Comment by rogermm14** [comment]
Hello ! Thank you for this comment.

When you run pytest with `tests/test_ba.py` the whole pipeline is launched from scratch. New files of keypoint matches are generated at each run. The keypoint matches from different runs may be slightly different (there are some elements within the matching that use randomized choices such as ransac) and lead to slightly different output coefficients.

I changed the matching strategy in `tests/test_ba.py`  (parameter `FT_sift_matching` of the configuration json/dict) to `bruteforce` instead of the previous `epipolar_based`. Both methods will give you nicely corrected RPCs, `bruteforce` is slower but allows more exact reproducibility and will avoid crashes with pytest.

**Comment by lionlai1989** [comment]
Thanks. It works.
